services:

  db:
    image: postgres:16-alpine
    container_name: estoque-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: estoque
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 413566
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d estoque"]
      interval: 10s
      timeout: 5s
      retries: 8
      start_period: 10s
    networks:
      - estoque-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estoque-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/estoque
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 413566
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - estoque-network

volumes:
  postgres_data:

networks:
  estoque-network:
    driver: bridge