spring.application.name=sistemaestoque

# Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/estoque
spring.datasource.username=postgres
spring.datasource.password=413566
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum_pool_size=10

# Configurações do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
# Chave para assinar os tokens
jwt.secret=

# Tempo de expieração do token
jwt.expiration=86400000

# Swagger
# URL da interface do Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Ordenação dos endpoints por mét0do
springdoc.swagger-ui.operationsSorter=method